config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: 'pages#home'
  get 'testing', to: 'pages#test'
  get 'index', to: 'carers#index'
  resources :users, only: %i[edit update]

  resources :carers, except: :destroy do
    resources :bookings
    resources :reviews, only: %i[index show]
  end
  resources :bookings do
    member do
      patch :update_status
    end
    get 'call', to: 'bookings#call'
    post 'call', to: 'bookings#call'
    get 'map', to: 'bookings#map'
    resources :reviews, except: %i[index show]
  end

  resources :patients, except: %i[destroy index] do
    resources :bookings, only: %i[index show call]
    resources :reviews, only: %i[new create index show]
  end
end

app/models/carer.rb
class Carer < ApplicationRecord
  REGION = %w[North South East West Center]
  SPECIALTY = ["Palliative Care", "Surgery Recovery Treatment", "Rehabilitation Care",
               "Assistance During Treatments", "Assistance and Providing Care",
               "Accomodative Care", "Injury Recovery Treatment"]
  has_one :user
  has_many :bookings, dependent: :destroy
  has_many :patients, through: :bookings

  # thanks to Cloudinary
  has_one_attached :photo

  validates :region, presence: true, inclusion: { in: REGION }
  # geocoded_by :address
  # after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/carers_controller.rb
class CarersController < ApplicationController
  before_action :set_carer, only: %i[edit update destroy]
  before_action :set_start_date
  helper_method :average_rating

  def index
    sql_query = "region ILIKE :region AND specialty ILIKE :specialty"
    region_query = "specialty ILIKE :specialty"
    @region = params[:region]
    @specialty = params[:specialty]

    if @region == "all"
      @carers = Carer.where(region_query, specialty: "%#{params[:specialty]}%")
    else
      @carers = Carer.where(sql_query, region: "%#{params[:region]}%", specialty: "%#{params[:specialty]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'list.html', locals: { carers: @carers }, formats: [:html] }
    end
  end

  def new
    @carer = Carer.new
  end

  def create
    @carer = Carer.new(carer_params)
    @carer.user_id = current_user.id
    User.find(@carer.user_id).role = 1
    @carer.specialty.gsub!("\"\",", "")
    if @carer.save
      redirect_to carer_path(@carer)
    else
      render :new
    end
  end

  def show
    @carer = Carer.find(params[:id])
    @bookings = Booking.where(start_date: @start_date.beginning_of_month.beginning_of_week..@start_date.end_of_month.end_of_week, carer_id: @carer)
    @specialty = JSON.parse(@carer.specialty)
    @reviews = Review.joins(:booking).where('bookings.carer_id = ?', @carer.id)
  end

  def edit; end

  def update
    if @carer.update(carer_params)
      redirect_to carer_path(@carer)
    else
      render :edit
    end
  end

  private

  # calculate average rating for a carer
  def average_rating(carer)
    @reviews = Review.joins(:booking).where('bookings.carer_id = ?', carer.id)
    @average_rating = 0
    @reviews.each do |review|
      @average_rating += review.rating
    end
    if @reviews.count.zero?
      return 0
    else
      return @average_rating /= @reviews.count
    end
  end

  def carer_params
    params.require(:carer).permit(:user_id, :photo, :region, specialty: [])
  end

  def set_carer
    @carer = Carer.find(params[:id])
  end

  def set_start_date
    @start_date = params.fetch(:start_date, Date.today).to_date
  end
end

app/views/carers/_calendarinfo.html.erb
<%= month_calendar(events: @bookings, attribute: :start_date, end_attribute: :end_date) do |date, bookings| %>
  <%= date.day %>
    <% bookings.each do |booking| %>
    <div class="booking">
        <% if booking.carer_confirmed? %>
          <div class = confirmed >
            <% @currpatient = User.find((Patient.find(booking.patient_id)).user_id).last_name %>
            <%= link_to @currpatient, booking_path(booking.id),  class: "btn-submit-yellow" %>
          </div>
          <% else %>
            <div class = notconfirmed >
              <% @currpatient = User.find((Patient.find(booking.patient_id)).user_id).last_name %>
              <%= link_to @currpatient, booking_path(booking.id),  class: "btn btn-submit-white" %>
            </div>
        <% end %>
    </div>
    <% end %>
<% end %>

app/views/carers/_calenderinfo.html.erb
<%= month_calendar do |date, bookings| %>
  <%= date %>
    <% bookings.each do |booking| %>
    <div class="booking">
      <p><%= User.find(booking.patient_id).last_name %></p>
    </div>
    <% end %>
<% end %>

app/views/carers/_cards.html.erb
<div data-refresh-list-target="cards">
  <div class="row">
    <% @carers.each do |carer| %>
        <div class="col-md-4">
          <div class="card" style="width: 18rem;">
            <div class="img">
              <%= cl_image_tag carer.photo.key, height: 300, width: 400, crop: :fill %>
            </div>
            <div class="card-body">
              <h2><%= User.find(carer.user_id).last_name %></h2>
              <p><%= User.find(carer.user_id).first_name %></p>
            </div>
            <div class="card-buttons">
              <%= link_to "More info", carer_path(carer), class: "btn btn-green" %>
              <% if current_user %>
                <%= link_to "Interview", "#",  class: "btn btn-green" %>
                <%= link_to "Book", "#",  class: "btn btn-green" %>
              <% end %>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/carers/_form.html.erb
<div class="form-container">
  <div class="carer-simple-form">
      <div>
        <%= simple_form_for(carer) do |f| %>
          <%= f.input :region, collection: Carer::REGION %>
          <%= f.input :photo, as: :file %>
          <%= f.input :specialty, as: :check_boxes, collection: Carer::SPECIALTY, input_html: { multiple: true }  %>
          <div>
            <%= f.submit 'Save my profile', class: "btn btn-submit-desaturated-cyan" %>
            <%= link_to 'Back', :back, class: "btn btn-submit-desaturated-cyan" %>
          </div>
        <% end %>
      </div>
  </div>
</div>

app/views/carers/_info_window.html.erb
<h2><%= carer.name %></h2>
<p><%= carer.address %></p>

app/views/carers/_list.html.erb
<div data-search-carers-target="list">
  <p class="h3">
    <% if params[:query].blank? %>
      <%= pluralize @carers.count, 'carer' %> available
    <% else %>
      <%= pluralize @carers.count, 'result' %> for <code><%= params[:query] %></code>
    <% end %>
  </p>
</div>
<div class="row">
  <% @carers.each do |carer| %>
    <div class="col-xs-9 col-sm-6 col-md-4">
      <div class="carer-card-border_4">
        <div class=<%= render 'shared/carer-card-style' %> >
          <div class="carer-photo">
            <div class="carer-img">
              <%= cl_image_tag carer.photo.key, height: 200, width: 200, crop: :fill %>
            </div>
          </div>
          <br>
          <div class="cards-body">
            <h2 style="color:#58abb7;"><%= User.find(carer.user_id).last_name %></h2>
            <p style="color:#58abb7;"><%= User.find(carer.user_id).first_name %></p>
          </div>
          <hr class="hr-carer-list">
            <div class="stars">
              <% stars = average_rating(carer).to_i %>
              <% stars.times do  %>
                <i class="fas fa-star"></i>
              <% end %>
            </div>
          <br>
          <div class="card-buttons">
            <% if user_signed_in? %>
              <% if current_user.id == carer.user_id %>
                <%= link_to "More info", carer_path(carer), class: "btn-submit-carer" %>
                <%= link_to "Edit my profile", edit_carer_path(carer.id),  class: "btn-submit-carer" %>
              <% elsif current_user.patient?%>
                <%= link_to "More info", carer_path(carer), class: "btn-submit-carer" %>
                <%= link_to "Book", new_carer_booking_path(carer.id),  class: "btn-submit-carer" %>
              <% end %>
            <% else %>
                <%= link_to "More info", carer_path(carer), class: "btn-submit-carer" %>
            <% end %>
          </div>
      </div>
        </div>
      </div>
  <% end %>
</div>

app/views/carers/calenderinfo.html.erb
<%= month_calendar(events: @bookings) do |date, bookings| %>
  <%= date %>
    <% bookings.each do |booking| %>
    <div class="booking">
      <p><%= User.find(booking.patient_id).last_name %></p>
    </div>
    <% end %>
<% end %>

app/views/carers/character_counter.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col">
      <h1>Character counter</h1>
      <div data-controller="character-counter" data-character-counter-limit-value="150">
        <textarea rows="3"
                  placeholder="Type something"
                  class="form-control mb-2"
                  data-action="keyup->character-counter#updateCounter"></textarea>
        <i data-character-counter-target="counter"></i>
      </div>
    </div>
  </div>
</div>

app/views/carers/edit.html.erb
  <%# the carer-background is the dive that contain the $navy-blue background %>
  <%# it's css is _carers_background %>
<div class="carer-background">
  <%# container_2 is the div that contains the white gradient %>
  <%# it's css is in _home.scss %>

    <div class="container_2">
      <div>
      <%= image_tag "icon-carer-edit.svg", class: "carer-edit-form-icon", alt:"#" %>
      </div>
        <div class="carers-new-form">
          <div class="row">
            <div class="col">
              <div class="form p-3">
                <%= render 'form', carer: @carer %>
              </div>
            </div>
          </div>
        </div>
    </div>

</div>

app/views/carers/index.html.erb
  <div class="container_clear">
        <h2 style="color:#58abb7;", class="my-3 d-flex justify-content-center"> <strong>Select a carer</strong> </h2>
          <div>
            <h3 style="color:#58abb7;",>Select by region</h3>
          </div>
        <div class="search-region">
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'north') do %>
              <%= image_tag "button_north.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'east') do %>
              <%= image_tag "button_east.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'south') do %>
              <%= image_tag "button_south.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'west') do %>
              <%= image_tag "button_west.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'center') do %>
              <%= image_tag "button_centre.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
            <div>
              <%= link_to(controller: 'carers', action: 'index', region: 'all') do %>
              <%= image_tag "button_show-all.svg", class: "direction-button", alt:"#" %>
              <% end %>
            </div>
        </div>
        <div class="search-specialty-dropdown">
         <div class="search-specialty">
          <a class="btn btn-region-search dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            <h4  id="specialty-h4">Select by specialty</h4>
          </a>

          <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Palliative Care', region: @region) do %>
                Palliative Care
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Surgery Recovery Treatment', region: @region) do %>
                Surgery Recovery Treatment
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Rehabilitation Care', region: @region) do %>
                Rehabilitation Care
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Assistance During Treatments', region: @region) do %>
                Assistance During Treatments
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Assistance and Providing Care', region: @region) do %>
                Assistance and Providing Care
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Accomodative Care', region: @region) do %>
                Accomodative Care
              <% end %>
            </li>
            <li class="dropdown-item">
              <%= link_to(controller: 'carers', action: 'index', specialty: 'Injury Recovery Treatment', region: @region) do %>
                Injury Recovery Treatment
              <% end %>
            </li>
          </ul>
         </div>
        </div>

    <div class="row">
      <div class="col">
        <%# <div data-controller="search-carers"> %>
        <%# <%= form_with url: carers_path, method: :get, html: { class: "mb-4", data: { search_carers_target: "form" } } do |f| %>
            <%# <%= f.text_field :query, %>
                           <%# class: "form-control", %>
                           <%# placeholder: "Choose a carer by region and specialty", %>
                           <%# value: params[:query], %>
                            <%# data: { %>
                              <%# action: "keyup->search-carers#update", %>
                              <%# search_carers_target: "searchInput" %>
                            <%# } %>
        <%# <% end %>
         <%= render "list", carer: @carers %>
        </div>
      </div>
    </div>
  </div>

app/views/carers/map.html.erb
<div class="pages-margin-top map-container" style="width: 100%; height: 600px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/carers/new.html.erb
    <div class="carer-background">
      <div class="container_2">
        <div>
          <%= image_tag "icon-carer.svg", class: "carer-new-form-icon", alt:"#" %>
          </div>
          <div class="carers-new-form">
            <div class="row">
              <div class="col">
                <div class="form p-3">
                  <%= render 'form', carer: @carer %>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>

app/views/carers/show.html.erb
<div class="carer-viewmore">
    <div class="carer-viewmore">
      <div class="carer-card-border_2">
            <div class=<%= render 'shared/carer-card-style' %> >
              <div class="carer-photo">
                <div class="carer-img">
                  <%= cl_image_tag @carer.photo.key, height: 200, width: 200, crop: :fill %>
                </div>
              </div>
              <div id="card-body-carer" class="card-body">
                <h2> <%= User.find(@carer.user_id).last_name %> </h2>
                <p> <%= User.find(@carer.user_id).first_name %> </p>
              </div>
              <div class="stars">
                <% stars = average_rating(@carer).to_i %>
                <% stars.times do  %>
                  <i class="fas fa-star"></i>
                <% end %>
              </div>
              <hr>


              <div class="carer-description">
                <h4> <strong> <%= pluralize @specialty.size, "specialty" %>: </strong> </h4>
                  <% @specialty.each do |spec| %>
                      <%= spec %> <br>
                  <% end %>
                <hr>
                <h4> <strong> Is located in the <%= @carer.region %>. </strong> </h4>
              </div>
            </div>
      </div>
            <div class="horizontal-scrolling-calendar">
              <div class="horizontal-scroll">
                <% if current_user.id == @carer.user_id %>
                  <%= render 'calendarinfo', carer: @carer %>
                <% end %>
              </div>
            </div>

            <div id="carer-viewmore-card" class="card-buttons">
              <% if current_user.id == @carer.user_id %>
                <%= link_to "Edit my profile", edit_carer_path(@carer.id),  class: "btn-submit-carer" %>
                <%= link_to "Reviews", carer_reviews_path(@carer.id) , class: "btn-submit-carer" %>
                <%= link_to "Back", carers_path, class: "btn-submit-carer" %>
              <% elsif current_user.patient?%>
                <%= link_to "Book", new_carer_booking_path(@carer.id),  class: "btn-submit-carer" %>
                <%= link_to "Reviews", carer_reviews_path(@carer.id) , class: "btn-submit-carer" %>
                <%= link_to "Back", carers_path, class: "btn-submit-carer" %>
              <% else %>
                <%= link_to "Back", carers_path, class: "btn-submit-carer" %>
              <% end %>
            </div>
    </div>
</div>