config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: 'pages#home'
  get 'testing', to: 'pages#test'
  get 'index', to: 'carers#index'
  resources :users, only: %i[edit update]

  resources :carers, except: :destroy do
    resources :bookings
    resources :reviews, only: %i[index show]
  end
  resources :bookings do
    member do
      patch :update_status
    end
    get 'call', to: 'bookings#call'
    post 'call', to: 'bookings#call'
    get 'map', to: 'bookings#map'
    resources :reviews, except: %i[index show]
  end

  resources :patients, except: %i[destroy index] do
    resources :bookings, only: %i[index show call]
    resources :reviews, only: %i[new create index show]
  end
end

app/models/booking.rb
class Booking < ApplicationRecord
  require 'twilio-ruby'
  belongs_to :carer
  belongs_to :patient
  has_many :reviews, dependent: :destroy

  validates :start_date, :end_date, presence: true

  CARER_CONFIRMED = ["Confirmed", "Not confirmed"]

  # All bookings will be ordered by their start_time by default
  default_scope -> { order(:start_date) }

  before_create :set_room_name

  # callback ActiveRecord
  def set_room_name
    client = Twilio::REST::Client.new(ENV["ACCOUNT_SID"], ENV["AUTH_TOKEN"])
    room = client.video.rooms.create(unique_name: "#{self.patient_id}_#{Time.now.to_i}")
    self.url_room = room.unique_name
  end

  def date
    "#{start_date.strftime('%I:%M %p')} - #{end_date.strftime('%I:%M %p')}"
  end

  def multi_days?
    (end_date.to_date - start_date.to_date).to_i >= 1
  end

  # def date_cannot_be_in_the_past
  #   if start_date.present? && start_date < Time.zone.now
  #     errors.add(:start_date, "can't be in the past")
  #   end

  #   if end_date.present? && end_date < Time.zone.now
  #     errors.add(:end_date, "can't be in the past")
  #   end
  # end

  # def start_must_be_before_end_time
  #   errors.add(:start_date, "must be before end time") unless
  #         start_date < end_date
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :set_carer, only: %i[new create]
  before_action :set_patient, only: %i[new show]

  def new
    if @carer.id == current_user
      flash[:danger] = 'You cannot book yourself!'
      redirect_to :back
    else
      @booking = Booking.new
    end
  end

  def create
    @booking = Booking.new(booking_params)
    @patient = Patient.where(user_id: current_user.id)[0]
    @booking.patient_id = @patient.id
    @booking.carer_id = @carer.id
    @booking.patient_confirmed = true
    if @booking.save
      flash[:notice] = "Booking request successfully created."
      redirect_to booking_call_path(@booking.id)
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @booking.update(booking_params)
      redirect_to carer_path(@booking.carer_id)
      flash[:notice] = "Booking successfully updated"
    else
      render 'edit'
    end
  end

  def update_status
    @booking = Booking.find(params[:id])
    @booking.update(carer_confirmed: params[:carer_confirmed])
    redirect_to carer_path(@booking.carer_id)
    flash[:notice] = "Booking confirmed!"
  end

  def index
    start_date = params.fetch(:start_date, Date.today).to_date
    @bookings = Booking.where(starts_at: start_date.beginning_of_month.beginning_of_week..start_date.end_of_month.end_of_week, carer_id: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    @patient = Patient.find(@booking.patient_id)
    @health_conditions = JSON.parse(@patient.health_conditions)
    @carer = Carer.find(@booking.carer_id)
    @specialty = JSON.parse(@carer.specialty)
  end

  def call
    @booking = Booking.find(params[:booking_id])
    @token = generate_token(@booking)
  end

  def map
    @booking = Booking.find(params[:booking_id])
    @patient = Patient.find(@booking.patient_id)
    @markers = [{lat: @patient.latitude, lng: @patient.longitude, image_url: helpers.asset_url("patient-geotag.svg")}]
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to carer_path(@booking.carer_id), notice: "Booking successfully deleted" }
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:carer_id, :patient_id, :start_date, :end_date, :patient_confirmed, :carer_confirmed)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_carer
    @carer = Carer.find(params[:carer_id])
  end

  def set_patient
    @patient = current_user
  end

  def generate_token(booking)
    # Create an Access Token
    token = Twilio::JWT::AccessToken.new ENV['ACCOUNT_SID'], ENV['SID'], ENV['KEY_ID'], [],
        ttl: 14400,
        identity: current_user.email
    # Grant access to Video
    grant = Twilio::JWT::AccessToken::VideoGrant.new
    grant.room = booking.url_room
    token.add_grant grant
    # Serialize the token as a JWT
    token.to_jwt
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def bookings_ajax_previous_link
    ->(param, date_range) { link_to raw("&laquo;"), {param => date_range.first - 1.day}, remote: :true}
  end

  def bookings_ajax_next_link
    ->(param, date_range) { link_to raw("&raquo;"), {param => date_range.last + 1.day}, remote: :true}
  end
end

app/views/bookings/_bookedcarer.html.erb
  <% user = User.find((Carer.find(@booking.carer_id)).user_id) %>
  <% carer = (Carer.find(@booking.carer_id)) %>
    <div class="carer-info">
    <hr>
      <h3>Name: <%= user.last_name %> <%= user.first_name %></h3>
      <h4><%= pluralize @specialty.size, "specialty" %>:</h4>
      <% @specialty.each do |spec| %>
        <%= spec %> <br>
      <% end %>

    <hr>
      <p>Start date: <%= (@booking.start_date).strftime('%A %d %B %Y %I:%M %p') %></p>
      <p>End date: <%= (@booking.end_date).strftime('%A %d %B %Y %I:%M %p') %></p> <br>
      <div class="patient-new-form">
            <% if @booking.carer_confirmed? && @booking.patient_confirmed?  %>
              <%= link_to "Leave a review", new_booking_review_path(@booking.id) , class: "btn-submit-carer" %>
            <% else %>
              <%= link_to "Edit your booking", edit_booking_review_path(@booking.id),  class: "btn btn-submit-yellow" %>
            <% end %>
      </div>
    </div>

app/views/bookings/_bookedpatient.html.erb
<div class="booked-patient">
  <% user = User.find((Patient.find(@booking.patient_id)).user_id) %>
  <% patient = Patient.find_by_user_id(user.id) %>
  <hr>
  <h3><%= user.last_name %> <%= user.first_name %></h3>
  <h3><%= pluralize @health_conditions.size, "Health condition" %>:</h3>
  <% @health_conditions.each do |cond| %>
    <%= cond %> <br>
  <% end %>
  <br>
  <br>

  <h3> Do you want to confirm your appointment</h3>

</div>
  <%= render 'carerconfirm', booking: @booking %>

app/views/bookings/_calendar.html.erb
<%= month_calendar bookings: bookings, previous_link: bookings_ajax_previous_link, next_link: bookings_ajax_next_link do |date, bookings| %>
  <%= date %>
<% end %>

app/views/bookings/_carerconfirm.html.erb
<div class="col-4x">
  <div class="cardx">
    <div class="two-buttons">
        <div class="carer-confirm-three-btn">
          <%= link_to "Call", booking_call_path(@booking.id), class:"btn btn-submit-desaturated-cyan-2" %>
          <%= link_to "Itinerary", booking_map_path(@booking.id),  class: "btn btn-submit-desaturated-cyan-2" %>
          <%= link_to 'Back', carer_path(@booking.carer_id), class: "btn btn-submit-desaturated-cyan-2" %>
        </div>
    </div>
      <hr>

      <div class="two-button-horizontal">
        <% if ! @booking.carer_confirmed? %>
          <%= link_to 'Confirm Booking', update_status_booking_path(@booking, carer_confirmed: :carer_confirmed), method: :patch, remote: true, class:"btn btn-submit-white-2" %>
        <% end %>
        <%= button_to "Reject Booking", @booking, method: :delete, remote: true, data: { confirm: 'Are you sure?' }, class:"btn btn-submit-white-2" %>
      </div>
  </div>
</div>

app/views/bookings/_form.html.erb
 <div class="booking-card">
    <%= simple_form_for [@carer, @booking] do |f| %>
      <h3>Book <%= User.find(@carer.user_id).first_name%> <%= User.find(@carer.user_id).last_name%> !</h3>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker" } %>
     <div class="patient-new-form">
        <%= f.submit class: 'btn-submit-carer' %>
        <%= link_to "Back", carer_path(@carer.id), class: "btn-submit-carer" %>
     </div>
    <% end %>
  </div>

app/views/bookings/_patientedit.html.erb
 <div class="booking-card">
    <%= simple_form_for [@booking] do |f| %>
      <h3>Reshedule your appointement with <%= User.find((Carer.find(@booking.carer_id)).user_id).first_name%> <%= User.find((Carer.find(@booking.carer_id)).user_id).last_name%> !</h3>
      <%= f.input :start_date, as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_date, as: :string, required: false, input_html: {class: "datepicker" } %>
      <%= link_to "Back", booking_path(@booking.id), class: "btn-submit-patient" %>
      <%= f.submit class: 'btn-submit-patient' %>
    <% end %>
  </div>

app/views/bookings/bookings.html.erb
<h1>Listing bookings</h1>

<%= month_calendar do |date| %>
  <%= date %>
<% end %>
<div id="bookings_calendar">
  <%= render partial: "calendar", locals: {bookings: @bookings} %>
</div>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start time</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.name %></td>
        <td><%= booking.start_time %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
        <td><%= link_to 'Destroy', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/call.html.erb
<div class="carer-card-border_2">
  <div class="carer-card-box-as-carer">
      <div class="title-wrapper">
        <div>
          <%= image_tag "video-call.gif", class:"video-icon-loading" %>
        </div>
        <hr>
        <div>
          <h3 class="title">A first contact with</h3>
          <h3 class="title">your NearbyCarer</h3>
        </div>
      </div>
    <div
      class="twilio-video"
      data-sid="<%= ENV["ACCOUNT_SID"] %>"
      data-room="<%= @booking.url_room %>"
      data-token="<%= @token %>"
      >

      <div class="justify-content-between">
        <div class="col-7">
          <div class="participant">

          </div>
        </div>
        <div class="col-4x">
          <div class="remote-media-div text-center">
            <div>
              <video id="userVideo" autoplay muted="true" ></video>
            </div>
            <div>
              <button id='leave-btn' class='btn'>
                <%= image_tag "button_endcall.svg", class: "endcall-button", alt:"#" %>
                <p style="opacity:0"> End this Conversation </p>
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-7xs">
        <p class="text-center">
          <%# <%= @booking.patient == current_user ? @booking.carer.email : @booking.patient.email %>
        </p>
       </div>
     </div>
      <% if current_user.carer? %>
      <%= link_to '', booking_path(@booking.id), class: 'd-none root-link', data: {turbolinks: false}  %>
      <% else %>
      <%= link_to '', carer_path(@booking.carer_id), class: 'd-none root-link', data: {turbolinks: false}  %>
      <% end %>
     </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<% if current_user.carer? %>
  <div class="booking-card-outline">
  </div>
    <div class="container">
      <h3>Do you want to confirm appointment with <%= User.find(Patient.find(@booking.patient_id)).last_name %></h3>
        <div class="carer-new-form">
          <div class="row">
            <div class="col">
              <div class="form p-3">
                <%= render 'carerconfirm', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% else %>
    <div class="container_2">
        <div class="patient-new-form">
          <div class="row">
            <div class="col">
              <div class="form p-3">
                <%= render 'patientedit', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <p><%= User.find((Patient.find(booking.patient_id)).user_id).last_name %></p>
  <p><%= booking.start_date %></p>
  <p><%= link_to 'Show', carer_booking(booking.id) %></p>
  <p><%= link_to 'Confirm Booking', edit_carer_booking(booking.id) %></p>
<% end %>

app/views/bookings/map.html.erb
<div style="width: 100%; height: 600px;"
  data-controller="mapbox"
  data-mapbox-markers-value="<%= @markers.to_json %>"
  data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

app/views/bookings/new.html.erb
<div class="booking-new">
  <div class="booking-card-outline">
      <div class="container_3">
        <%= image_tag "booking-carer.gif", class:"new-booking-gif", alt:"booking-image" %>
        <div class="patient-new-form">
          <div class="row">
            <div class="col">
              <div class="form p-3">
                <%= render 'form', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/bookings/show.html.erb
<% if current_user.carer? %>
  <div class="booking-card-outline">

    <div class="carer-card-box-as-carer">
      <div class="booking-confirm-title">
        <h4>Details on patient <%= User.find((Patient.find(@booking.patient_id)).user_id).last_name %></h4>
      </div>
        <div class="carer-new-form">
          <div class="rowx">
            <div class="colx">
              <div class="form p-3">
                <%= render 'bookedpatient', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% else %>
    <div class="container">
    <%= image_tag "icon-your-booking.svg", class:"logo-sm" %>
    <h3>Details on carer <%= User.find((Carer.find(@booking.carer_id)).user_id).last_name %></h3>
        <div class="patient-new-form">
          <div class="row">
            <div class="col">
              <div class="form p-3">
                <%= render 'bookedcarer', booking: @booking %>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

app/views/bookings/test.html.erb
<div class="title-wrapper">
  <div class="container">
    <h1 class="title">Your NearbyCarer online</h1>
  </div>
</div>
<div class="container">
  <div
    class="twilio-video"
    data-sid="<%= ENV["ACCOUNT_SID"] %>"
    data-room="<%= @booking.url_room %>"
    data-token="<%= @token %>"
    >

    <div class="row justify-content-between">
      <div class="col-7">
        <div class="participant">
        </div>
      </div>
      <div class="col-4">
        <div class="remote-media-div text-center">
          <video id="userVideo" autoplay muted="true" ></video>
          <div>
            <button id='leave-btn' class='btn btn-submit-carer'>
              End Conversation
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-7">
      <p class="text-center">
        <%# <%= @booking.patient == current_user ? @booking.carer.email : @booking.patient.email %>
      </p>
      </div>
    </div>
    <%= link_to '', root_path, class: 'd-none root-link', data: {turbolinks: false}  %>

  </div>
</div>