config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: 'pages#home'
  get 'testing', to: 'pages#test'
  get 'index', to: 'carers#index'
  resources :users, only: %i[edit update]

  resources :carers, except: :destroy do
    resources :bookings
    resources :reviews, only: %i[index show]
  end
  resources :bookings do
    member do
      patch :update_status
    end
    get 'call', to: 'bookings#call'
    post 'call', to: 'bookings#call'
    get 'map', to: 'bookings#map'
    resources :reviews, except: %i[index show]
  end

  resources :patients, except: %i[destroy index] do
    resources :bookings, only: %i[index show call]
    resources :reviews, only: %i[new create index show]
  end
end

app/views/shared/_background-color.html.erb
    <% if user_signed_in? %>
      <% if current_user.role == "carer" %>
        "navy-blue-carer-background"
       <% else current_user.role == "patient" %>
          "gradient-patient-background"
    <% end %>
    <% else %>
        "gradient-patient-background"
    <% end %>

app/views/shared/_carer-card-style.html.erb
    <% if user_signed_in? %>
      <% if current_user.role == "carer" %>
        "carer-card-box-as-carer"
       <% else current_user.role == "patient" %>
          "carer-card-box-as-patient"
    <% end %>
    <% else %>
        "carer-card-box-as-patient"
    <% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer>
  <div class="footer">
    <p>© 2022 Copyright: Nearby Care</p>
  </div>
</footer>

app/views/shared/_nabar-styling-logo.html.erb
<% if user_signed_in? %>
  <% if current_user.role == "carer" %>
    <%= image_tag "nearby-care-logo-white-crop.svg" %>
  <% else current_user.role == "patient" %>
    <%= image_tag "nearby-care-logo-crop.svg" %>
  <% end %>
<% else %>
  <%= image_tag "nearby-care-logo-crop.svg" %>
<% end %>

app/views/shared/_navbar-styling-color.html.erb
<% if user_signed_in? %>
      <% if current_user.role == "carer" %>
        "navbar navbar-expand-sm navbar-lewagon navbar-carer"
       <% else current_user.role == "patient" %>
          "navbar navbar-expand-sm navbar-lewagon navbar-patient"
    <% end %>

    <% else %>
        "navbar navbar-expand-sm navbar-lewagon navbar-patient"
    <% end %>

app/views/shared/_navbar.html.erb
<div>
  <div class=<%= render 'shared/navbar-styling-color' %>>
    <div class="container-fluid">
      <%= link_to root_path, class: "navbar-brand" do %>
        <% if user_signed_in? %>
            <% if current_user.role == "carer" %>
                    <%= image_tag "nearby-care-logo-white-crop.svg" %>
                <% else current_user.role == "patient" %>
                    <%= image_tag "nearby-care-logo-crop.svg" %>
                <% end %>
                <% else %>
                <%= image_tag "nearby-care-logo-crop.svg" %>
            <% end %>
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
            <% if user_signed_in? %>
                <% if current_user.role == "carer" %>
                    <%= image_tag "burger-menu-white.svg" %>
                <% else current_user.role == "patient" %>
                    <%= image_tag "burger-menu.svg" %>
                <% end %>
                <% else %>
                    <%= image_tag "burger-menu.svg" %>
            <% end %>
        </span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Our Carers", carers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <% if user_signed_in? %>
            <% if current_user.role == "carer" %>
                <%= cl_image_tag ((Carer.find_by_user_id(current_user.id)).photo.key), class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else current_user.role == "patient" %>
                <%= image_tag "patient-icon-navbar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <% else %>
                <%= image_tag "patient-icon-navbar.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Edit my credentials", edit_user_registration_path, class: "dropdown-item" %>
              <% if Patient.find_by_user_id(current_user.id).present? %>
                <%= link_to "My profile", patient_path(Patient.find_by_user_id(current_user.id)), class: "dropdown-item" %>
              <% elsif Carer.find_by_user_id(current_user.id).present? %>
                <%= link_to "My profile", carer_path(Carer.find_by_user_id(current_user.id)), class: "dropdown-item" %>
              <% else %>
                <%= link_to " ", class: "dropdown-item" %>
              <% end %>
              <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Our Carers", carers_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>