config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: 'pages#home'
  get 'testing', to: 'pages#test'
  get 'index', to: 'carers#index'
  resources :users, only: %i[edit update]

  resources :carers, except: :destroy do
    resources :bookings
    resources :reviews, only: %i[index show]
  end
  resources :bookings do
    member do
      patch :update_status
    end
    get 'call', to: 'bookings#call'
    post 'call', to: 'bookings#call'
    get 'map', to: 'bookings#map'
    resources :reviews, except: %i[index show]
  end

  resources :patients, except: %i[destroy index] do
    resources :bookings, only: %i[index show call]
    resources :reviews, only: %i[new create index show]
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  CONDITIONS = ["Terminal illnesses", "Brain surgery", "Hip and knee replacements", "Complex fractures",
                "Neurological disorders", "Diabetes", "Back injury", "Spinal cord injury", "Alzheimer",
                "Dialysis", "Chronic illness", "Accident Injury Recovery", "Sports Injury Treatment"]
  has_one :user
  has_many :bookings, dependent: :destroy
  has_many :carers, through: :bookings
  has_many :reviews, through: :bookings

  validates :address, presence: true
  # validates :health_conditions, inclusion: CONDITIONS
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    @patient.user_id = current_user.id
    @patient.health_conditions.gsub!("\"\",", "")
    if @patient.save
      redirect_to carers_path
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @booking = Booking.new
    @patients = Patient.all
    @patient = Patient.find_by_user_id(current_user)
    @health_conditions = JSON.parse(@patient.health_conditions)
    @markers = @patients.geocoded.map do |patient|
      if patient.user_id == current_user.id
        {
          lat: patient.latitude,
          lng: patient.longitude
        }
      end
    end
  end

  def edit; end

  def update
    if @patient.update(patient_params)
      redirect_to patient_path(@patient)
    else
      render :edit
    end
  end

  private

  def patient_params
    params.require(:patient).permit(:user_id, :address, health_conditions: [])
  end

  def set_patient
    @patient = Patient.find(params[:id])
  end
end

app/views/patients/_form.html.erb
<div class="form-container">
  <div class="simple-form" data-controller= "geocoder">
    <%= simple_form_for(patient) do |f| %>
      <%= f.input :address,
          input_html: { data: { geocoder_target: "address" }, class: "d-none" },
          wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'], action: "load@window->geocoder#geocode" } } %>
        <%= f.input :health_conditions, as: :check_boxes, collection: Patient::CONDITIONS, input_html: { multiple: true }  %>
      <div class="patient-new-form">
        <%= f.submit 'Save my profile', class: "btn btn-transparent-blue" %>
            <%= link_to 'Back', :back, class: "btn btn-transparent-blue" %>
      </div>
    <% end %>
  </div>
</div>

app/views/patients/destination.html.erb
<div class="pages-margin-top map-container" style="width: 100vw; height: 100vh;"
  data-controller="destination"
  data-destination-markers-value="<%= @marker.to_json %>"
  data-destination-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
<div class="d-flex align-items-center btn-container">
  <%= link_to "Go to patient's place ?", patient_address_path(@path), class: "btn btn-custom " %>
</div>

app/views/patients/edit.html.erb
<div class="container">
        <%= image_tag "icon-user-edit.svg", class:"logo-sm" %>
  <div class="row">
    <div class="col">
      <div class="form p-3">
        <%= render 'form', patient: @patient %>
      </div>
    </div>
  </div>
</div>

app/views/patients/new.html.erb
<div class="container">
  <div>
      <%= image_tag "icon-patient.svg", class: "patient-new-form-icon", alt:"#" %>
  </div>
    <div class="patient-new-form">
      <div class="row">
        <div class="col">
          <div class="form p-3">
            <%= render 'form', patient: @patient %>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/patients/show.html.erb
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div >
          <div class="container-transparent_2">
          <%= image_tag "patient-icon-profile.svg", class:"logo-sm" %>
            <h3><%= User.find(@patient.user_id).last_name %></h3>
            <h3><%= User.find(@patient.user_id).first_name %></h3>
            <hr>
            <p><%= @patient.address %></p>
            <h4><%= pluralize @health_conditions.size, "Health condition" %>:</h4>
                <% @health_conditions.each do |cond| %>
                  <%= cond %> <br>
                <% end %>
                <hr>
          </div>
          <div class="patient-new-form">
            <%= link_to "Back", carers_path, class: "btn btn-submit-yellow-2" %>
            <% if current_user.id == @patient.user_id %>
              <%= link_to "Edit my profile", edit_patient_path(@patient.id),  class: "btn btn-submit-yellow-2" %>
              <%= link_to "Your booking", booking_path(Booking.where(patient_id: (Patient.find_by_user_id(current_user.id)).id).last),  class: "btn btn-submit-yellow-2" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>